### ISSUE TITLE
Unable to visualise `/camera/imu` in Rviz

### ISSUE THREAD

**Issue by tsadarsh** [CCNYRoboticsLab/imu_tools#170]
I have installed `rviz_tools`  from `apt`. I am using **ROS2 Humble** in my _Pop!_OS 22.04 LTS_.
My IMU source is from an IntelRealsense D435i stereo camera which has an integrated IMU inside it.
When my `realsense2_camea` node is up I have a `/camera/imu` topic. I have included a sample echo message that it publishes:
```
header:
  stamp:
    sec: 1669733293
    nanosec: 890969088
  frame_id: camera_imu_optical_frame
orientation:
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance:
- -1.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
angular_velocity:
  x: 0.005235987715423107
  y: -0.003490658476948738
  z: 0.0
angular_velocity_covariance:
- 0.01
- 0.0
- 0.0
- 0.0
- 0.01
- 0.0
- 0.0
- 0.0
- 0.01
linear_acceleration:
  x: 1.5690639019012451
  y: 2.0299766063690186
  z: 9.32612419128418
linear_acceleration_covariance:
- 0.01
- 0.0
- 0.0
- 0.0
- 0.01
- 0.0
- 0.0
- 0.0
- 0.01
---
```
I open up Rivz (ros2 run rviz2 rviz2), fix the **Fixed Frame** to to `camera_link` and add a new display for `Imu`:
![image](https://user-images.githubusercontent.com/66778010/204564753-91e0bbf6-107e-4ca6-9338-d1aedded72d0.png)
![image](https://user-images.githubusercontent.com/66778010/204567312-2c549a89-cbfe-48b3-b191-bf812e71c8b9.png)

But the IMU axes are stationary (even though the `/camera/imu` topic updates in real time).

`ros2 topic info /camera/imu` gives:
>ros2 topic info /camera/imu
Type: sensor_msgs/msg/Imu
Publisher count: 1
Subscription count: 1

Why are the IMU axes in Rviz not updating?
