### ISSUE TITLE
Issue with imu_filter_madgwick in slope when using a magnetometer

### ISSUE THREAD

**Issue by avanmalleghem** [CCNYRoboticsLab/imu_tools#195]
Hello,

I want to fuse my magnetometer with my IMU (relative) in ROS using imu_filter_madgwick.
My setup is quite simple :
- I have a magnetometer driver node publishing sensor_msgs/msg/MagneticField messages in mag_link frame (fixed frame relative to base_link)
- I have an IMU driver node publishing sensor_msgs/msg/Imu messages in imu_link frame (fixed frame relative to base_link)

I have a imu_filter_madgwick node with the following parameters : 
```
/imu_filter_madgwick:
  ros__parameters:
    constant_dt: 0.0
    declination: 0.0
    fixed_frame: odom
    gain: 0.6
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 0.1
    publish_debug_topics: true
    publish_tf: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    remove_gravity_vector: false
    reverse_tf: false
    stateless: false
    use_mag: true
    use_sim_time: false
    world_frame: enu
    yaw_offset: 1.57
    zeta: 0.0
```

The output of the imu_filter_madgwick is correct when we are on a planar environment. The issue is that the yaw is incorrect when we have a slope. I mean that I expect to have a constant yaw in a slope (the orientation in yaw should not change but unfortunately it does). I expected this node to solve the slope complexity. Did I miss something ? 

I use version 2.1.3 on ROS2 Humble

Thanks in advance for your answer.
