### ISSUE TITLE
Z axis points downwards if magnetometer does not publish during some seconds

### ISSUE THREAD

**Issue by csimon-be** [CCNYRoboticsLab/imu_tools#211]
Hi,

I am working with the **imu_filter_madgwick** package and have encountered some behavior that I do not understand.

Using the package with a magnetometer, we noticed that sometimes our robot's heading turns in the opposite direction when turning in place. After a certain delay, it returns to normal.

The issue seems to originate from the data published on /imu/data (output from the Madgwick filter), and it is observable in Rviz. To confirm this hypothesis, it is reproducible with another magnetometer we tested. Therefore, it confirms that the issue is not with the device itself but with our Madgwick filter configuration. I believe our IMU configuration is correct (Z is positive and points upwards).

For the record, here is our **imu_filter_madgwick.yaml** configuration:
```
imu_filter_madgwick:
  ros__parameters:
    gain: 0.1
    zeta: 0.0
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 0.1

    world_frame: enu
    use_mag: true
    use_magnetic_field_msg: true
    publish_tf: false
    constant_dt: 0.0
    publish_debug_topics: true
    stateless: false
    remove_gravity_vector: false
```

To reproduce the issue:

1. Launch the code.
2. Unplug the power supply of the magnetometer.
3. Wait for 5 seconds.
4. Plug it back in.

You'll notice that the axis rotates when you plug it back in (the z-axis points downwards instead of upwards). It slowly returns to normal after some time. The longer you wait, the more disoriented it gets.

I have attached a video demonstrating the steps described above. Once I plug the magnetometer back in, you can see the axes are completely disoriented. Increasing the gain helps to recover faster, but I would prefer to avoid this disorientation altogether. Can you help me, please?

[Screencast from 10-10-2024 12:11:51 PM.webm](https://github.com/user-attachments/assets/c62620b8-bad6-4801-918e-311ac6a879f6)

Thanks in advance,
Kind regrads,

Christophe
